### ISSUE TITLE
Motorola e5 Play, Android 8.1 - testing notes

### ISSUE THREAD

**Issue by mzorz** [Automattic/portkey-android#158]
These are my notes from testing on a Motorola e5 Play, Android 8.1

- [x] it rotates and then you have a black screen (fixed in https://github.com/Automattic/portkey-android/pull/129)
- [ ] sometimes saving the image gives a `Failed to save File` error  https://github.com/Automattic/portkey-android/issues/122#issuecomment-533521705

#### Stretching preview mode
- [ ] the **Video Player mode** after you save a video shows a bit too wide or stretched towards the center vertically, and seemed pixelated.
- however, the **recorded video output** was viewed super well ✅ 

#### Other
- [ ] can't capture still image, it just doesn't trigger and says operation in progress (possibly related work to be done re: https://github.com/Automattic/portkey-android/issues/134)
- [ ] if I try to save video, it starts, but after a few seconds it crashes https://github.com/Automattic/portkey-android/issues/159
- [ ] emoji picker has all emoji cut on the side #161
