### ISSUE TITLE
[Primary] Adapt gesture listeners to cope with new width/height fontSize handling

### ISSUE THREAD

**Issue by mzorz** [Automattic/portkey-android#207]
As part of tackling #153, #205, #66 and probably #180, we're changing the pinch to zoom behavior to change the TextView's fontSize to the extent it's applicable, and then only manipulate the View's `scale` when fontSize has already reached a limit.

This is applicable to views based on `TextView` (emoji and text), but is not applicable to views based on `ImageView`(animated gif and such).

For this, several things need be done:
PART 1:
- [x] use some way to change fontSize when resizing the View (#204)

PART 2:
- [x] set a maximum to avoid this
```2019-11-22 09:11:14.763 9332-9378/com.automattic.portkey E/OpenGLRenderer: Font size too large to fit in cache. width, height = 359, 338``` (#206)

PART 3: 
- [x] scale / rotate: either reconnect the old listener and use scale / rotate as well, or implement rotation on the new simplified listener (#208)
- [x] re-implement the "delete view" in the new listener https://github.com/Automattic/portkey-android/pull/209
- [x] make sure all the pre-existing functionality works as expected https://github.com/Automattic/portkey-android/pull/210 (re-wiring Text handling)

PART 4:
- [x] add a callback interface on AutoResizeTextView to let the listener know when the maximum / minimum font size has been reached, so the gesture detector can stop sending shrink/zoom signals to the view (if minimum reached), or switch to SCALING change when the maximum FontSize has been reached. See #211 and #214 

PART 5:
- [ ] evaluate whether it makes sense to handle `ImageView` separately with the old, pre-existing listeners (could potentially be a step in the meantime), or incorporate the scale listener mechanism within the new listener scheme (in which case, we should remove the old classes if they end up not being used). EDIT: added handling of images with the new listener in https://github.com/Automattic/portkey-android/pull/210/commits/926b3cef026129bb2c4fcd591f67499058a3b4fb in #210
