### ISSUE TITLE
Publishing flow

### ISSUE THREAD

**Issue by mzorz** [Automattic/portkey-android#276]
- [x] Save frame service #273
- [x] add notifications for saving (see error handling) #282
- [x] Bottom sheet #194
~- [ ] integration with FluxC #195~ no need to integrate with FluxC as we provide files inteads of Media
- [x] integrate upload service #267 
~- [ ] upload service notifications #268~  keeping the ones existing in WPAndroid
