### ISSUE TITLE
Frame Save error handling [Primary issue]

### ISSUE THREAD

**Issue by mzorz** [Automattic/portkey-android#282]
The process to save, upload, and successfully publish a story is complex, potentially lengthy, and has a number of different points of failure.

The *tldr;* version of the story publishing process:

1. Composing – When a user decides to publish a Story, the app processes each story page and saves it to the local device disk.
2. Uploading – Once all the story pages are saved locally, the process of uploading each page to the site begins.
3. Publishing – Once each story page is uploaded, the story is published to the site.

In regards to Portkey itself, we're only dealing with part 1/3 above (steps 2 and 3 belong to / are implemented by WPAndroid). 

### Visual cues during the Composing phase

There are mainly three UI components we're using to signal the user about something the app is doing during the Composing/Saving phase:

- a. system notifications (error, ~success~, progress)
- b. error dialogs plus exclamation mark on errored frames at the bottom strip
- c. snackbars (when the user is away of the composing screen and a process starts, and when it ends either successfully or with error)

For point (a) above we already have the ~success~ _(we don't need a success notification, as it's going to be just one final notification that is already part of the Upload process in WPAndroid)_ and progress notifications (#279) in place.
That means we need to implement:

- [x] Basic error collection and Error notification (PR #281 )
- [x] Error dialogs (issue #284) PR #290
- [x] process steps Snackbars (issue #283) PR #286 
- [x] Error handling view (issue #285)

#### System Notifications

In the following chart, the notifications on the right side correspond to the Error, Progress/foreground, and Success notifications for the existing upload process in WPAndroid.

The notifications shown on the left, correspond to the Error and Progress/foreground notifications for the Story Frame Save process. while the last one left is the success notification for Publishing (on WPAndroid side).

![system-notifications-2](https://user-images.githubusercontent.com/6597771/76644240-5f042280-6535-11ea-87df-39113edba1d3.png)

#### Error flow
The following image shows the error flow, with system notifications, dialogs and snackbars all along:

![error-flow](https://user-images.githubusercontent.com/6597771/76644249-61ff1300-6535-11ea-8fca-de5e81445fb2.png)

#### Error handling view
After an error saving one or more frames has been detected, a Dialog is presented indicating details about the error. Once the dialog is dismissed, the user is presented with the composing screen where they can try and fix the errors:
<img width="1039" alt="Screen Shot 2020-03-24 at 10 24 34" src="https://user-images.githubusercontent.com/6597771/77430395-e1080d00-6db9-11ea-862e-e25e47fd4d26.png">

#### Snackbars

This shows the successful snackbars (we'll use the variant on the left, with the Story title)

![successful-snackbar-text-2](https://user-images.githubusercontent.com/6597771/76644256-64616d00-6535-11ea-9309-81bb93cb0aa7.png)

#### Success flow (happy path)

And this one shows the successful publish flow (happy path - no errors)
![successful-publish-flow](https://user-images.githubusercontent.com/6597771/76644257-64fa0380-6535-11ea-8c56-e46ec20a162d.png)

#### Summarizing

Saving a Story could appear like this (_note: taken from a conversation held elsewhere and narratively summarizing how things would look like for the user_):

1. Composing Progress notification is shown and reads `Composing / saving "Spring in Tokyo" - 2 pages remaining`

2. if something happens while this step is taking place, then according to the designs an error notification `Unable to upload "Spring in Tokyo"` would appear. Note that the stage at which the failure occurs is not really the `Upload` step (2) but the `Save` step (1. composing), however I understand the message `Unable to upload` still is descriptive enough (as it conveys that, in the current condition, the Story cannot be uploaded after all). At this point, the rest of the process is halted (including the remaining processing / composition and of course the Upload step), and action is required 👍🏻.

3. (WPAndroid) if nothing bad happens while composing / saving all the Story frames, then we start the Upload phase: the Composing progress notification is dismissed and the normal Upload progress notification appears. (both will look very similar, but progress will make it to 100% on each phase given these are 2 separate services). I can try and see if I can reuse the same notification, but for a first pass I’d assume we’ll have to use 2 separate ones.

4. (WPAndroid) The upload process itself may end up successfully (and hence the Story gets published right away) in which case we show the success system notification. Tapping on the success notification takes you either to viewing the Story or, if this is your first story, a special screen that prompts you to share your first story is presented (*)

5. (WPAndroid) In the case of error uploading: regardless of this part of the process being retried automatically by the WP app when a connection becomes available (this was implemented for offline support), the app still shows the error notification just the same way as it’d currently for Posts / Pages. The user can tap “Retry” on the Notification and the Upload process will take place from where it left, and eventually the Story will get published if no other errors are found. (same retry action could be done from the Story list, but that’s as you mentioned covered on an upcoming p2 post of yours).

(*) *OPTIONAL/TBD* we may have implement a dialog or screen we show for one time for the first Story published by a user on the app.
